services:
  firewall:
    image: debian:12
    container_name: firewall
    hostname: firewall
    networks:
      dmz_net:
        ipv4_address: 192.168.1.2
      private_net:
        ipv4_address: 192.168.0.2
    privileged: true
    command: /bin/bash -c "
      apt update &&
      apt install -y iptables ufw &&
      ufw default deny incoming &&
      ufw allow from any to 192.168.1.3 port 80 proto tcp &&
      ufw allow from any to 192.168.1.3 port 443 proto tcp &&
      ufw allow from 192.168.0.0/24 to 192.168.1.3 port 22 proto tcp &&
      ufw enable &&
      tail -f /dev/null"

  server:
    image: debian:12
    container_name: server
    hostname: server
    networks:
      dmz_net:
        ipv4_address: 192.168.1.3
    privileged: true
    command: /bin/bash -c "
      apt update &&
      apt install -y nginx ufw &&
      echo '<h1>Bienvenue sur le serveur sécurisé</h1>' > /var/www/html/index.html &&
      ufw allow 80/tcp &&
      ufw allow 443/tcp &&
      ufw enable &&
      nginx -g 'daemon off;'"
    ports:
      - "8080:80"

  client:
    image: debian:12
    container_name: client
    hostname: client
    networks:
      private_net:
        ipv4_address: 192.168.0.3
    command: /bin/bash -c "
      apt update &&
      apt install -y curl nmap &&
      tail -f /dev/null"

networks:
  private_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

  dmz_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

