Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"  # Debian 12
  config.vm.hostname = "client"
  config.vm.network "private_network", ip: "192.168.0.11"

  config.vm.provider : virtualbox

  config.vm.provision "shell", inline: <<-SHELL
    apt update && apt upgrade -y
    apt install -y curl nmap
  SHELL
end
