Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"  # Debian 12
  config.vm.hostname = "server"
  config.vm.network "private_network", ip: "192.168.0.10"

  config.vm.provision "shell", inline: <<-SHELL
    apt update && apt upgrade -y
    apt install -y nginx ufw

    ufw allow 22   # SSH
    ufw allow 80   # HTTP
    ufw allow 443  # HTTPS
    ufw enable

    systemctl restart nginx
  SHELL
end
